### ISSUE TITLE
Marvin pip install issues in windows 11

### ISSUE THREAD

**Issue by echohive42** [PrefectHQ/marvin#114]
I tried installing marvin as per the instructions(in a new virtual environment). During the installation I got some errors before pip installation was somewhat successfully completed:

![image](https://user-images.githubusercontent.com/122702381/228989739-b8328d3f-a50b-4c23-823f-8ed04e82740f.png)

But when I run "marvin chat" command in the command prompt of my VS Code then nothing happens  and I don't receive an error either. 

I know this is not much information but this is all I have. 

Thank you in advance for any assistance :)

**Comment by yichenchong** [comment]
It looks like you have some outdated packages. Try using `pip install --upgrade` on the packages that it says are incompatible. Also, if all else fails, try upgrading pip itself and then upgrade the packages again.

**Comment by echohive42** [comment]
Ok I will try that. I think gujicorn will have a problem because I think it is only for Unix(not sure). will update here.

**Comment by zzstoatzz** [comment]
closing, should be solved by #172
