### ISSUE TITLE
Non-descriptive error when SSL certificate not configured correctly

### ISSUE THREAD

**Issue by csreuter** [PrefectHQ/marvin#116]
After upgrading to Python 3.10, `certifi` was not set up correctly. After installing `marvin`, I could run `openai-setup` and set my api key, but upon running `marvin chat` the message would retry ~6 times and surface error `APIConnectionError: Error communicating with OpenAI`. 

The full stacktrace revealed several SSL-related errors. I ended up running `certificates.command` within my root Python folder, after which SSL was set up correctly.

Consider creating more robust error messaging around `APIConnectionError: Error communicating with OpenAI`, as this may be a common new user failure point.

**Comment by ryantbrennan1** [comment]
@csreuter I am running into this issue as well. Can you explain what you did to fix this? Not sure what `certificates.command` is. Thanks~

**Comment by csreuter** [comment]
@ryantbrennan1 

It is a file that should be in the  */Applications/Python 3.x" folder wherever Python is installed. Just have to execute it. Alternatively I think you could just run [this](https://gist.github.com/marschhuynh/31c9375fc34a3e20c2d3b9eb8131d8f3).

Once I ran that it updates my SSL certificates and this library worked!

**Comment by jlowin** [comment]
I'm going to close this because I don't think it's a Marvin issue, it's a Mac Python issue - best practice would be to use a virtual env or conda distribution rather than system Python
