### ISSUE TITLE
Observation about LLM Response

### ISSUE THREAD

**Issue by VishDev12** [PrefectHQ/marvin#118]
I noticed that in a number of cases, these lines in your prompt:

https://github.com/PrefectHQ/marvin/blob/3cc01e4684ea10cf9666b373b6092eba0137644e/src/marvin/bots/response_formatters.py#L90-L91

have an outsized effect on the response from the LLM.

When the response type of an `ai_fn` wrapped function was `str`, I got this from gpt-3.5: `{"title": "Model", "type": "string"}`

And when the response type was `dict`, I got: `{"title": "Model", "type": "object"}`.

Failure when return type was string seems more likely. And for context, I captured these outputs directly after the `response = await self._call_llm(messages=messages)` line.

Perhaps this issue might only be faced with 3.5 since it doesn't always understand highly detailed instructions, but I just wanted to make note of it anyway.

---

Great job on the code and the tool! Pleasure to read through!

**Comment by jlowin** [comment]
Appreciate the feedback -- this is indeed a 3.5 failure mode that we haven't quite been able to work around. In many other structured cases, especially with Pydantic models, the schema hint gives dramatically better results, but occasionally it messes up (especially with sets and tuples, which should print a warning on 3.5). These prompts are live and I'm trying to write test cases to avoid regression so if you experiment let us know!

**Comment by jlowin** [comment]
I believe we've significantly improved this in many cases (including #121) so I'm going to close the issue but if you identify specific ai_fns that result in bad outputs, please open issues to address them as test cases!
