### ISSUE TITLE
Issue with greenlet library on M1 Mac

### ISSUE THREAD

**Issue by ezra-risq** [PrefectHQ/marvin#119]
Having trouble with the greenlet library on an M1 mac. (Searching around I see this issue with M1 macs for other libraries that use greenlet but haven't found a good solution yet. Specific error is: 

> ValueError: the greenlet library is required to use this function. dlopen(/Users/eball/miniconda3/envs/marvin/lib/python3.10/site-packages/greenlet/_greenlet.cpython-310-darwin.so, 0x0002): tried: '/Users/eball/miniconda3/envs/marvin/lib/python3.10/site-packages/greenlet/_greenlet.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

Ideas for workarounds welcome.

**Comment by discdiver** [comment]
Marvin (on GPT 3.5) suggests installing with homebrew. Not sure if you tried that already.
![Screenshot 2023-03-31 at 10 40 35 AM](https://user-images.githubusercontent.com/7703961/229151897-4052c04a-150a-4516-893e-e10d039c0ffb.png)

**Comment by zzstoatzz** [comment]
hi @ezra-risq - hmm, I wonder if updating your xcode cmd line tools would do anything here?

**Comment by discdiver** [comment]
Are you trying in a conda or venv virtual environment with Python 3.10 installed? If not, perhaps try that and install greenlet into that environment.

**Comment by seanpwlms** [comment]
I had this issue in a 3.10 conda environment.  I also tried it with Rosetta and had the same issue.

**Comment by zzstoatzz** [comment]
hi @seanpwlms - can you share what action you took when you encountered this error? just on install?

**Comment by seanpwlms** [comment]
Yeah, just on install and trying to run it
```
conda create -n marv-env python==3.10
conda activate marv-env
pip install marvin
marvin chat
```
That gives me the greenlet error.
`arch` returns i386

**Comment by seanpwlms** [comment]
@ezra-risq Circling back on this, I think I had a caching problem. I was able to fix the install by uninstalling, then running `pip cache purge` and reinstalling (not using Rosetta).
