### ISSUE TITLE
JS/TS version & a few questions

### ISSUE THREAD

**Issue by transitive-bullshit** [PrefectHQ/marvin#122]
This is phenomenal 🔥 

I'd love to help add TS support for the core `ai_fn` decorator.

1. What are your internal plans for JS/TS support?
2. How much is tied to Marvin the company & platform vs being an agnostic tool like LangChain that can call into any hosted or local LLM provider?
3. Any advice on where to start either in this monorepo or separately on a JS/TS port of the `ai_fn` functionality in particular?

Thanks && congrats on your public launch! 🙏

**Comment by zzstoatzz** [comment]
hi! 

1. we don't have any plans to add JS/TS support at this time

2. marvin is currently an independent project and we're more opinionated than agnostic (in the sense that we're specifically built on the OpenAI chat model interface / ChromaDB etc). I could see us potentially adding support for different LLMs in the future though

3. hmm I'm not sure - @jlowin do you have any thoughts in this regard?

**Comment by adamwatters** [comment]
@transitive-bullshit any plans to take this on / have you started working on it? i'd love to help!
