### ISSUE TITLE
I don't have the ability to visit external websites

### ISSUE THREAD

**Issue by MattiRajobit** [PrefectHQ/marvin#146]
Homepage says the following about bot plugins.
Plugins[¶](https://www.askmarvin.ai/guide/concepts/bots/#plugins)
Plugins allow bots to access new information and functionality. By default, bots have plugins that let them browse the internet, visit URLs, and run simple calculations.

When I am trying to ask bot to access a website and ask it questions, it tells me following:
"
│ I'm sorry for the confusion earlier. As an AI language model, I don't have the ability to visit external websites.  │
│ However, I can still provide some feedback based on what you tell me about your website or any other website you're │
│ interested in.
"

Is bots allowed to browse the internet and visit URLs?

**Comment by zzstoatzz** [comment]
hi @MattiRajobit 

if you instantiate a normal bot like

```python

from marvin.bots import Bot

my_bot = Bot()
```

it should have the following

```python
DEFAULT_PLUGINS = [
    marvin.plugins.web.VisitURL(),
    marvin.plugins.duckduckgo.DuckDuckGo(),
    marvin.plugins.mathematics.Calculator(),
]
```

can you share how you instantiated your bot if it was different from that? otherwise there could be a bug related to the plugin defaults

**Comment by MattiRajobit** [comment]
Hi. Thank you for your reply and help! 
I checked that my bot has those plugins.
I also did some more research and it seems that the problem is the website I am trying to access. 

I tried to access website: "https://www.rajobit.com/" and couldn't get result, however when I tried other website it worked.  

When I tried to find it as: "https://www.rajobit.com/en-gb" it worked. Any ideas why? Maybe the Finnish language is causing problems. Sorry for bothering.



Here is the conversation log:
HumanMessage(content='Visit a URL and return its contents https://www.rajobit.com/',
                             additional_kwargs={})
[04/03/23 05:27:38] DEBUG    marvin.Bot: AI message: I'm sorry, but I can't visit that URL as it seems to be misspelled or it   logging.py:60                             is not responding. Is there another website you would like me to visit and analyze?


I also checked that the plugins were same as what you listed.

**Comment by zzstoatzz** [comment]
interesting... I agree it does seem the failure is related to the language on the website 🤔 

If you were able to provide the full DEBUG logs from when this happened, it might be more clear, but overall I agree with your assessment here
> it seems that the problem is the website I am trying to access.
