### ISSUE TITLE
Enable user customization of instruction templates

### ISSUE THREAD

**Issue by outday29** [PrefectHQ/marvin#157]
Thank you for making this awesome tool available for everyone!

I noticed that the instructions templates of the bots (and its corresponding parameters in the Jinja template) are hardcoded in `bots/base.py` (defined in `INSTRUCTIONS_TEMPLATE`). I also noticed similar pattern in `ai_fn` defined in `ai_functions.py`. The instructions template for user message (defined in `AI_FN_MESSAGE` constant) is hardcoded, resulting in users having little control on what user message being sent to the OpenAI model. 

I was wondering if there is any plan to allow users to configure their own instruction templates. I feel that the default template can be a bit restrictive sometimes as its longer length does not always go well with the shorter context length in GPT 3.5. Besides, I feel having a different bot instruction template for different use cases may result in a more efficient prompts and better performance.

Thanks :)

**Comment by zzstoatzz** [comment]
hi @outday29 

I like the idea of being able to customize instruction templates so I've went ahead and opened a PR that adds `instructions_template` as a field on `Bot` - how does that sound?

Note that `Bot._get_bot_instructions` would still be passing the template the same variables [here](https://github.com/PrefectHQ/marvin/pull/158/files#diff-ae4fb7311d1937fa2c530ea14fac41f27f959c50d21c202e950f6fbf19e4f26fR458), which means that whatever custom template str you create would still be expecting those variables when rendering

**Comment by outday29** [comment]
Yeah, that sounds good to me. Understood that it will be an unstable feature. Thanks for your help!

**Comment by zzstoatzz** [comment]
Hi @outday29 - this is merged into main but not yet released - closing this issue

let us know if you encounter any issues!
