### ISSUE TITLE
incorrect API is being delivered to the OpenAI server.

### ISSUE THREAD

**Issue by ElCuboNegro** [PrefectHQ/marvin#175]
1. given the following: sk-wJOK3***************************************fjYz
2. I get: 

`AuthenticationError: Incorrect API key provided: sk-nuLlk***************************************dhN2. You can find your API key at https://platform.openai.com/account/api-keys.`

probably due I have past config from other API in my envs.

**Comment by zzstoatzz** [comment]
hi @ElCuboNegro - thanks for the issue!

can you share which version of `marvin` you're on? also can you share whether you setup your openai key via `marvin setup-openai` or not?

**Comment by ElCuboNegro** [comment]
first time, manually, then through marvin setup-openai.

the version is the one in the commit f74377d

**Comment by jlowin** [comment]
Marvin looks for the API key in the following places in order:

1. the `MARVIN_OPENAI_API_KEY` env var
2. the `OPENAI_API_KEY` env var

Both are first checked dynamically and then in a `.env` file at `~/.marvin/.env` which is written by setup-openai. So setup-openai *should* take precedence over even a global `OPENAI_API_KEY` env var. 

Can you check your env vars and the `.env` file to see if that second key got stored somewhere?

**Comment by ElCuboNegro** [comment]
done, I was aware how to fix it, but I though it was not the expected behavior.
