### ISSUE TITLE
Support Azure OpenAI API

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/marvin#189]
See: https://news.ycombinator.com/item?id=35498110

It looks like this has support in Langchain via the Chat API: https://python.langchain.com/en/latest/modules/models/chat/integrations/azure_chat_openai.html

**Comment by geertjan-garvis** [comment]
Did this locally for my own use, seems to work ok so far. can clean up to be ready for merge. 
https://github.com/PrefectHQ/marvin/pull/271

**Comment by TheodoreGalanos** [comment]
This would be really cool if it's ready to go :) Just bumping it.

**Comment by TheodorosGalanos** [comment]
Just bumping this one.

It seems like the above is obsolete with the new version of marvin. And Azure support is not longer there.

This would be useful given that a lot of enterprise solutions are running on Azure OpenAI right now.

Happy to test an implementation, although not sure I can patch one myself.

**Comment by jlowin** [comment]
See #476 #475 #477
