### ISSUE TITLE
Upgrading to 0.7.4 leads to database error when using `marvin chat`

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/marvin#195]
context: 

# Name                    Version                   Build  Channel
marvin                    0.7.1                    pypi_0    pypi

same with 0.7.4

`marvin chat`

results in the TUI displaying and then a very log error message that concludes with the following:

```
...
OperationalError: (sqlite3.OperationalError) no such column: bot_config.created_at
[SQL: SELECT bot_config.created_at, bot_config.updated_at, bot_config.plugins, bot_config.input_transformers, 
bot_config.id, bot_config.name, bot_config.personality, bot_config.instructions, 
bot_config.instructions_template, bot_config.description, bot_config.profile_picture 
FROM bot_config 
WHERE bot_config.name = ?
 LIMIT ? OFFSET ?]
[parameters: ('Marvin', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

Running a script with an AI function completes with the correct output, but also throws the error:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: bot_config.created_at
[SQL: SELECT bot_config.created_at, bot_config.updated_at, bot_config.plugins, bot_config.input_transformers, bot_config.id, bot_config.name, bot_config.personality, bot_config.instructions, bot_config.instructions_template, bot_config.description, bot_config.profile_picture 
FROM bot_config 
WHERE bot_config.name = ?
 LIMIT ? OFFSET ?]
[parameters: ('DuetBot', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by zzstoatzz** [comment]
I also worked with a user to resolve this in discord, they were able to resolve after a db upgrade

it seems there's still some weirdness with adding the default bots for the tui experience @jlowin

**Comment by discdiver** [comment]
Throwing away the db in ~/.marvin resolved the problem.

**Comment by zzstoatzz** [comment]
reopening, deleting the db is not a solution for users who have data in their db

**Comment by jlowin** [comment]
I *believe* that @discdiver's particular version of this problem will not affect users broadly because the `created_at` column was not included in the original development migration but I re-added it prior to release because it turns out SQlite can't add columns with dynamic defaults, so there was no way to add it in a migration. So I'm pretty sure the only way to not have a created_at column is if your database was created during the brief window in which it wasn't part of the initial migration. 

However I have a PR that should further smooth this out

**Comment by abrookins** [comment]
If it helps, I had 0.6.4 installed and hit this error after I upgraded to 0.7.4.

**Comment by discdiver** [comment]
Closing, as I got a nice db upgrade prompt when I upgraded marvin to 0.7.5. 👍
