### ISSUE TITLE
If I already have the default bots installed, the TUI should not have an install button

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/marvin#241]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the current behavior

I already have the default bots installed. I click on "Bots". The TUI has a  "Install default bots" button, which is confusing. A user might think the bots are not installed and that they need to install each bot individually.

<img width="1017" alt="Screenshot 2023-04-21 at 10 42 58 PM" src="https://user-images.githubusercontent.com/7703961/233762986-bf11d7dc-0c51-45a6-b592-0b894cc6ad13.png">

### Describe the proposed behavior

The "Install Default Bots" button should only show if the default bots are not installed.

**Comment by nickkatsios** [comment]
Hi, i could work on this if that's okay.

**Comment by jlowin** [comment]
One issue here is that we don't currently have a concept of what a "default" bot is (or a "bot library"), so determining whether all of the bots exist and are unmodified is an open question
