### ISSUE TITLE
Can't Install Requests and Marvin at the same time.

### ISSUE THREAD

**Issue by Xirious** [PrefectHQ/marvin#256]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Some incompatiblities between `requests` and `marvin`. Dependencies can't be resolve due to differing requirements on multiple packages.

Also appears marvin's fixed version of `trafilatura==1.5.0` has some incompatibilities as well.

### Reproduction

# Try 1 - requirements.in
```
requests>=2.28.1
marvin>=0.8.0
```

> pip-compile -o requirements.txt requirements.in

# Try 2 - requirements.in
```
requests==2.23.0
marvin>=0.8.0
```

> pip-compile -o requirements.txt requirements.in

### Error
# Try 1

```python3

WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
Using legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.
Could not find a version that matches charset-normalizer<3,>=2,>=3.1.0 (from requests==2.28.1->-r etc/requirements.in (line 31))
Tried: 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.5, 1.3.6, 1.3.6, 1.3.7, 1.3.7, 1.3.8, 1.3.8, 1.3.9, 1.3.9, 1.4.0, 1.4.0, 1.4.1, 1.4.1, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 2.0.2, 2.0.2, 2.0.3, 2.0.3, 2.0.4, 2.0.4, 2.0.5, 2.0.5, 2.0.6, 2.0.6, 2.0.7, 2.0.7, 2.0.8, 2.0.8, 2.0.9, 2.0.9, 2.0.10, 2.0.10, 2.0.11, 2.0.11, 2.0.12, 2.0.12, 2.1.0, 2.1.0, 2.1.1, 2.1.1, 3.0.0, 3.0.0, 3.0.0, 3.0.1, 3.0.1, 3.0.1, 3.1.0, 3.1.0, 3.1.0
Skipped pre-versions: 0.1a0, 0.1.1a0, 0.1.2b0, 0.1.4b0, 0.1.5b0, 3.0.0b1, 3.0.0b1, 3.0.0b2, 3.0.0b2, 3.0.0rc1, 3.0.0rc1, 3.0.0rc1
There are incompatible versions in the resolved dependencies:
  charset-normalizer<3,>=2 (from requests==2.28.1->-r etc/requirements.in (line 31))
  charset-normalizer>=3.1.0 (from trafilatura==1.5.0->marvin==0.8.0->-r etc/requirements.in (line 32))
```

# Try 2
```python3
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
Using legacy resolver. Consider using backtracking resolver with `--resolver=backtracking`.
Could not find a version that matches chardet<4,>=3.0.2,~=5.1 (from marvin==0.8.0->-r etc/requirements.in (line 32))
Tried: 1.0, 1.0.1, 1.1, 2.1.1, 2.2.1, 2.2.1, 2.3.0, 2.3.0, 3.0.0, 3.0.0, 3.0.1, 3.0.1, 3.0.2, 3.0.2, 3.0.3, 3.0.3, 3.0.4, 3.0.4, 4.0.0, 4.0.0, 5.0.0, 5.0.0, 5.1.0, 5.1.0
There are incompatible versions in the resolved dependencies:
  chardet<4,>=3.0.2 (from requests==2.23.0->-r etc/requirements.in (line 31))
  chardet~=5.1 (from marvin==0.8.0->-r etc/requirements.in (line 32))
```

### Versions

- Trying to install `marvin` version `0.8.0`
- `pip-compile`, version `6.13.0`
- Python `3.11.3`

### Additional context

- First try using the latest version of requests.
- Second try using an older, fixed version of requests.
- Problems arise with charset-normalizer and chardet due to incompatibilities.

**Comment by Xirious** [comment]
I think using the `--resolver=backtracking` fixed it. 

It took an inordinate long time to generate the requirements but it did in the end. Thank you and my apologies for having wasted your time. I should have tried that before posting the ticket. 

PS: I don't mind changing tools (this is for a personal project) but using another dependency manager is not necessarily possible in some production systems so I think this should be left up as a warning to those who can not change from pip-tools.

**Comment by zzstoatzz** [comment]
@Xirious thank you for the feedback! glad you "resolved" (pun intended) :)
