### ISSUE TITLE
Project Related: auto-rust

### ISSUE THREAD

**Issue by bregydoc** [PrefectHQ/marvin#280]
Hello everyone!

First of all, I must commend the `marvin` project - it's truly fantastic! I am currently working on an experimental project inspired `marvin`. In this project, I am exploring the concept of "AI Functions" in Rust, generating code at compile time using the OpenAI API. I believe that utilizing auto-implemented functions at compile time in Rust may not be the most scalable way to write code. However, I also think it's crucial to investigate the full spectrum of possibilities within programming languages. If anyone is interested, you can view and test this experiment at https://github.com/minskylab/auto-rust.

**Comment by zzstoatzz** [comment]
closing this as it is not as issue so much as a discussion point - this could be re-opened as a discussion!
