### ISSUE TITLE
Add setting to output all text at once instead of typing/scrolling output with TUI

### ISSUE THREAD

**Issue by derekschrock** [PrefectHQ/marvin#287]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the current behavior

For long responses the typing/autoscrolling rendering can be rather jarring causing the UI to shift/flicker/jump until the full response has finished rendering.

### Describe the proposed behavior

Can setting be added, off by default if the current display style is preferred, to display the output or a response all at once eliminating the  typing/autoscrolling?

### Example Use

A toggle/checkbox in the settings window.

**Comment by derekschrock** [comment]
If I could choose I'd rather disable the stream text all together.   So I would say it's a purely negative thing.

**Comment by jlowin** [comment]
@derekschrock what terminal are you using? There hopefully shouldn't be any flickering. Is it Apple's builtin terminal.app?

**Comment by derekschrock** [comment]
marvin running in tmux on FreeBSD 13.1 where I'm sshing from macOS with macports using kitty built from source.
