### ISSUE TITLE
TUI chat interface hides underlying API errors

### ISSUE THREAD

**Issue by phelbas** [PrefectHQ/marvin#304]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the current behavior

Created a new open-ai key, installed everything, tried to use TUI chat and an error shows that is quickly occluded by the full screen interface. Had to screen record to pause on a frame to see what the error was.
It was that open-ai expired everyones free API credits worth $18.00, some time after you signed up as a regular user -- even if you never had an API key. (Perhaps put that in quick start notes. That unless you are a new sign-up to open-ai, your API key may not work without paying for a plan, even though you generated it today).

### Describe the proposed behavior

The chat interface needs to by default capture lower level errors and display them in some way, for example to stderr so if you quit you can see them, instead of silently failing.

**Comment by lh8** [comment]
I may be experiencing the same issue. 

Screencast here >
https://github.com/PrefectHQ/marvin/assets/457857/f339272f-e904-4c3c-850f-3ca096841752
