### ISSUE TITLE
Noncopyleft dependency issue

### ISSUE THREAD

**Issue by lalitpagaria** [PrefectHQ/marvin#314]
First thank you for this great project. While using it in our org project I found that it listed one required dependency `trafilatura`, which is GPL3 licensed. This conflicts with Marvin's license (Apache2). Can we make it an optional dependency under `copyleft` flag so users who are adding be aware explicitly.

**Comment by zzstoatzz** [comment]
thanks for the flag @lalitpagaria! I've opened a PR to put `trifilatura` behind a `copyleft` extra

**Comment by lalitpagaria** [comment]
Thanks you @zzstoatzz 
Is it a good idea to add info about extras in readme as well?

**Comment by zzstoatzz** [comment]
hi @lalitpagaria - we've now done a full rewrite of the library and it should no longer contain any GPL3 deps, all should be Apache, MIT or BSD

you can install the new version from `main` (release coming soon)
```
pip install git+https://github.com/PrefectHQ/marvin.git
```

and verify yourself with something like
```console
pip-licenses --format=plain | rg GPL3
```
