### ISSUE TITLE
Support concurrent .map patterns for AI Components.

### ISSUE THREAD

**Issue by aaazzam** [PrefectHQ/marvin#437]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the current behavior

I ran ai_fn/ai_model/ai_classifier once. I want to run it in parallel or concurrently. 

### Describe the proposed behavior

Add .map method similar to Marvin 0.X in marvin[framework] that uses Prefect to orchestrate. 

@zzstoatzz ?

**Comment by zzstoatzz** [comment]
`ai_fn` aspect of this issue has been addressed by #441

**Comment by dleebrown** [comment]
+1 to this, for `ai_classifier` in particular, since batch classification tasks almost always perfectly parallelizable.
