### ISSUE TITLE
Plans to upgrade to Pydantic v2?

### ISSUE THREAD

**Issue by chrisgoddard** [PrefectHQ/marvin#538]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the proposed behavior

Hey guys - just curious whether there are current plans to upgrade to Pydantic v2?

**Comment by discdiver** [comment]
Completed in #594 and released in v 1.5
