### ISSUE TITLE
Add docs example of using multiple tools in AI Application

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/marvin#559]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the current behavior

I wasn't sure whether Marvin supported running two tools in a row in a single call, so I wrote a short example to test, and it worked.

### Describe the proposed behavior

```python
import random
from marvin import AIApplication
from marvin.tools import tool
from pydantic import BaseModel


class Memory(BaseModel):
    roll_history: list[list[int]] = Field(default_factory=list)


@tool
def roll_dice(n_dice: int = 1) -> list[int]:
    print("Rolling")
    return [random.randint(1, 6) for _ in range(n_dice)]


@tool
def sum_dice(rolls: list[int]) -> int:
    print(f"Summing {rolls}")
    return sum(rolls)


state = Memory()
chatbot = AIApplication(
    description="Help get the total of the rolls",
    tools=[roll_dice, sum_dice],
    state=state,
)

response = chatbot("Roll two dice!")
print(response.content, response.state)
```

**Comment by zzstoatzz** [comment]
yo @ahuang11!! hope you're doing well :) - thanks for the issue! will do
