### ISSUE TITLE
ai_fn for False boolean returns are broken in 1.5.4

### ISSUE THREAD

**Issue by bevanhunt** [PrefectHQ/marvin#621]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Upgrading from 1.5.3 to 1.5.4 breaks ai_fn functions that return a False boolean value. This happens because rather than returning `False` it returns `output=False`.

### Reproduction

```python3
@ai_fn
def is_a_question(user_question:str) -> bool:
"""You check if the user's question: `user_question` is a question."""

is_a_question("You make me happy Marvin.")
should return False
returns output=False
```

### Versions

```Text
1.5.4
Python 3.11.6
```

**Comment by zzstoatzz** [comment]
thank you for the report @bevanhunt - we'll get on this asap

**Comment by zzstoatzz** [comment]
interesting - looks like this bug had to do with a `if not <output>` check where we should have had a `if <output> is None`

this bug should only exist in the case where an `ai_fn` literally returns `False` - like your example above. #622 should fix this and I can release as soon as its merged

thanks again for the report!
