### ISSUE TITLE
1.5.6 has an update_state tools bug

### ISSUE THREAD

**Issue by bevanhunt** [PrefectHQ/marvin#635]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Running my AI application creates this error now:

ValueError Function update_state not found in function_registry

'UpdateState': marvin.functions.UpdateState(patches: list[marvin.components.ai_application.JSONPatchModel])}

### Reproduction

```python3
Create an AI application with multiple tools and run the AI Application.
```

### Error

```python3
/app/.heroku/python/lib/python3.11/site-packages/marvin/components/ai_application.py:256
return run_sync(self.run(input_text=input_text, model=model))
```

### Versions

```Text
Marvin 1.5.6
Python 3.11.6
```

**Comment by nengisuls** [comment]
I'm also getting an error. Update_state not found in function registry.
