### ISSUE TITLE
1.5.6 has ai_model bool always True bug

### ISSUE THREAD

**Issue by bevanhunt** [PrefectHQ/marvin#639]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

When using a bool field in an ai_model the value will always return as True.

### Reproduction

```python3
@ai_model(model=gpt35)
class PlacesSearch(BaseModel):
    """A Google Places search."""
    open_now: bool = Field(..., description="This should always be `False`.")

params = PlacesSearch("What is the best sushi bar?").dict()
print(params['open_now']) => True


@ai_model(model=gpt35)
class PlacesSearch(BaseModel):
    """A Google Places search."""
    open_now: str = Field(..., description="This should always be `False`.")

params = PlacesSearch("What is the best sushi bar?").dict()
print(params['open_now']) => "False"
```

### Error

```python3
N/A
```

### Versions

```Text
Marvin 1.5.6
Python 3.11.6
```

**Comment by nengisuls** [comment]
I'm also getting an error. Update_state not found in the function registry.
