### ISSUE TITLE
Allow AI functions to generate source code

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/marvin#64]
If AI functions could generate source code and execute it, they could do significantly more on the local machine. However, this would constitute untrusted code and would require controls to avoid unintended execution.

**Comment by ElCuboNegro** [comment]
perhaps you can use two instances of the AI_FN functions:

the first one should take the user request and transform it into the function signature and docstring (in my experience, it works very well when you ask for the signature with a google style docstring with examples)
other for ask for the test the function has to pass.

then you can generate, with GPT4 (0.7 in temperature) the function and test it with. and repeat until the test has been pass.

**Comment by justquick** [comment]
an artificially created test passing does not constitute trust in the underlying function, simply correctness. it would need some amount of guardrails or sandboxing to ensure there are no unintended/destructive side effects of the code execution. dont completely trust the machines. this is exactly how skynet starts

**Comment by ElCuboNegro** [comment]
True, but you can safeward through non-ai static analysis

**Comment by zzstoatzz** [comment]
[closing ](https://www.askmarvin.ai/src/reference/components/ai_function/#code-generation)
