### ISSUE TITLE
ChatCompletion Function Calling & `response_model` Not Working

### ISSUE THREAD

**Issue by jteppinette** [PrefectHQ/marvin#674]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

I can't get the `response_model` to work with function calling with `ChatCompletion`.

### Reproduction

```python3
class A(BaseModel):
    name: str


def get_data() -> str:
    ...

with ChatCompletion(functions=[get_data], response_model=A) as chat:
    chat.send(messages=User(prompt).generate())

    while conversation.last_turn.has_function_call():
        conversation.send(
            messages=[conversation.last_turn.call_function()],
        )
```

```
ValueError: Function Product not found in function_registry={}.
```

However, if you remove the `while` loop, then the error is not raised. Of course, then the functions won't be called. I have tried placing the `response_model` in the send/s vs chatcompletion object, and I can't get them to work with both function calling and response_model.
```


### Error

_No response_

### Versions

```Text
1.5.6
```

**Comment by zzstoatzz** [comment]
hi @jteppinette - here's how you could do this in marvin 2:
```python
In [1]: from marvin import fn

In [2]: def get_style() -> str:
   ...:     return "early north american cowboys"
   ...:

In [3]: @fn
   ...: def say_something() -> str:
   ...:     return f"in the style of {get_style()}"
                    DEBUG    marvin.Tools: FormatResponse: called with arguments: {'value': 'Howdy, partner!'}
                    DEBUG    marvin.Tools: FormatResponse: returned: Howdy, partner!
Out[4]: 'Howdy, partner!'
```
