### ISSUE TITLE
GPT-4 version 0613 deprecate functions/function_calls

### ISSUE THREAD

**Issue by weburnit** [PrefectHQ/marvin#686]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the current behavior

supporting functions which is deprecated

### Describe the proposed behavior

next version support tools/tool_calls
https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools

### Example Use

```
curl https://api.openai.com/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $OPENAI_API_KEY" \
-d '{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "What is the weather like in Boston?"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string",
              "description": "The city and state, e.g. San Francisco, CA"
            },
            "unit": {
              "type": "string",
              "enum": ["celsius", "fahrenheit"]
            }
          },
          "required": ["location"]
        }
      }
    }
  ],
  "tool_choice": "auto"
}'

```

### Additional context

Please advice me which branch to start developing this feature.
I've developed on my machine but not sure which branch to start with.

**Comment by zzstoatzz** [comment]
hi @weburnit - sorry for the delayed response.

im going to close this as marvin 2 supports openai tools at this time, feel free to raise any issues you're having!
