### ISSUE TITLE
add cookbook entry to auto-merge/close select Dependabot PRs

### ISSUE THREAD

**Issue by zzstoatzz** [PrefectHQ/marvin#700]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the current behavior

DNE

### Describe the proposed behavior

some script / flow that (given some GH credentials) in `cookbook/` that's triggered by the creation of a PR from dependabot that also accepts some heuristics from the user on what dependabot should merge.

the script should produce some numerical confidence that the PR should be merged and:
- merge if very confident that it should be merged based on heuristics
- notify maintainer for resolution if unsure (or do nothing)
- close if sure it should _not_ be merged based on heuristics

an `Assistant` might be useful here

**Comment by cyai** [comment]
@zzstoatzz I have created a pr trying to create one such python script. Please take a look and let me know if there are any necessary changes to be made. 

Am happy to work on it for any changes (:
