### ISSUE TITLE
Setting a model not working for proxies

### ISSUE THREAD

**Issue by anjor** [PrefectHQ/marvin#714]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

I have built a simple streamlit app using Marvin - https://github.com/anjor/quiz-game

The app also makes use of the [Radiant platform](https://radiantai.com/). One of the features of Radiant is the ability to route requests to different providers without changing the client side code. So you can have your application with OpenAI code and point it to some other provider like say Mistral.

I started wiring this up -- https://github.com/anjor/quiz-game/pull/1/files

However, I noticed that despite choosing a different model (like mistral-tiny) the requests were still being sent to gpt-3.5-turbo. What's the best way to change the model?

### Reproduction

```python3
https://github.com/anjor/quiz-game/pull/1/files
```

### Versions

```Text
Version:		1.5.6
Python version:		3.11.6
OS/Arch:		darwin/arm64
```

### Additional context

https://twitter.com/__anjor/status/1742197814174584833

**Comment by zzstoatzz** [comment]
hi @anjor - I'm not sure exactly about Radiant and not so familiar with mistral's sdk yet, but in `marvin` 2 we expose these settings:
- `marvin.settings.openai.base_url`
- `marvin.settings.chat.completions.model`

such that if you're using a clone of OpenAI's api (I think litellm does mistral [here](https://docs.litellm.ai/docs/providers/mistral)) you should be able to have marvin send requests according to your `base_url` and `model` setting values
