### ISSUE TITLE
Add support for classifying lists (in addition to literals / enums)

### ISSUE THREAD

**Issue by jlowin** [PrefectHQ/marvin#722]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the current behavior

Today classifiers require either literals or enums, and use a convenience function to turn those into "vocabularies".

### Describe the proposed behavior

As a convenience, allow users to provide lists of objects (probably strings, though any enumerable object with a good repr should work). This would make it easier to dynamically classify as well.

### Example Use

```python
marvin.classify("Lets make classification better!", ["feature request", "bug report"]) 
# "feature request"
```

^ equivalent to `marvin.classify(..., Literal['feature request', 'bug report'])`

**Comment by zzstoatzz** [comment]
this functionality is now available as of `marvin>=2.1.x`
