### ISSUE TITLE
Broken import in Marvin from OpenAI client version 1.8.0

### ISSUE THREAD

**Issue by krishnan-chandra** [PrefectHQ/marvin#765]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

The `HttpxBinaryResponseContent` import [moved inside the OpenAI library between release 1.7.2 and 1.8.0](https://github.com/openai/openai-python/compare/v1.7.2...v1.8.0#). This breaks Marvin's import of this class, which causes Marvin not to be importable on fresh installs. 

This problem can be temporarily solved by pinning the `openai` library to the 1.7 minor version: `openai = "~1.7.0"`

### Reproduction

```python3
python -m venv marvin_openai_test_env
source marvin_openai_test_env/bin/activate
pip install marvin==2.1b1
python -c "import marvin"
```

### Error

```python3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/krishnanchandra/marvin_test_env/lib/python3.11/site-packages/marvin/__init__.py", line 3, in <module>
    from .ai.text import fn, cast, extract, classify, classifier, generate, model, Model
  File "/Users/krishnanchandra/marvin_test_env/lib/python3.11/site-packages/marvin/ai/__init__.py", line 2, in <module>
    from . import audio
  File "/Users/krishnanchandra/marvin_test_env/lib/python3.11/site-packages/marvin/ai/audio.py", line 4, in <module>
    from openai._base_client import HttpxBinaryResponseContent
ImportError: cannot import name 'HttpxBinaryResponseContent' from 'openai._base_client' (/Users/krishnanchandra/Projects/HUMINT/marvin_test_env/lib/python3.11/site-packages/openai/_base_client.py)
```

### Versions

```Text
2.1b1
```

**Comment by zzstoatzz** [comment]
thanks for the report @krishnan-chandra - the fix should now be released with 2.1b2

`pip install marvin==2.1b2`
