### ISSUE TITLE
Update README Only After New Version is Released on PyPI

### ISSUE THREAD

**Issue by Fakamoto** [PrefectHQ/marvin#767]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the current behavior

Marvin repo updates README with new features that are not present in the version you get when you install marvin with `pip install -U marvin`

### Describe the proposed behavior

README should match the latest version you get when you install the latest stable version of marvin. 

This would avoid a lot of confusion.

**Comment by zzstoatzz** [comment]
sorry for any confusion - you can install today's release with `pip install marvin==2.1b1`

**Comment by Fakamoto** [comment]
Okay then maybe a good idea to update README in the main branch to tell users to install marvin with `pip install marvin==2.1b1` instead of `pip install -U marvin` here https://github.com/PrefectHQ/marvin?tab=readme-ov-file#installation
