### ISSUE TITLE
Format string for "created_at" in assistant not valid

### ISSUE THREAD

**Issue by maccam912** [PrefectHQ/marvin#795]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Format string on the line here: https://github.com/PrefectHQ/marvin/blob/60a891f66057604f185d68cbf905d5904cea8972/src/marvin/beta/assistants/formatting.py#L154

Is just not a valid format string.

I am pretty sure the %l (lower case L) is supposed to instead be %I (upper case i).

### Reproduction

```python3
from datetime import datetime
datetime.fromtimestamp(100).strftime("%l:%M:%S %p")
```

### Error

```python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid format string
```

### Versions

```Text
Version:                2.1.2
Python version:         3.10.8
OS/Arch:                windows/amd64
```

### Additional context

I have seen this with the latest version in various versions of python.

**Comment by zzstoatzz** [comment]
thank you @maccam912 - lowercase L appears to work on unix but not windows. I've gone ahead and merged [your update](https://github.com/PrefectHQ/marvin/pull/796)
