### ISSUE TITLE
Async model/cast/extract calls

### ISSUE THREAD

**Issue by pietz** [PrefectHQ/marvin#798]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the proposed behavior

With the possibility of using LLMs for data extraction also comes the challenge of scaling it. Currently marvin only supports synchronous calls/clients for models (right?). I would like to have an option to do it asynchronously, so I can call external APIs with more than one request at once.

I saw that there is a `AsyncMarvinClient` but either it only works for assistants or I don't know how to use it.

### Example Use

```python
client = AsyncMarvinClient(...)
res = await marvin.cast(data, PydanticModel, client=client)
```

**Comment by zzstoatzz** [comment]
hi @pietz - this should now be on `main` via #802 and will be released shortly

```python
In [1]: import marvin

In [2]: from typing import Literal

In [3]: Sentiment = Literal["good", "bad"]

In [4]: await marvin.classify_async("these empanadas are the bees knees", Sentiment)

Out[4]: 'good'

```

**Comment by pietz** [comment]
Phenomenal. Thank you very much!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zzstoatzz** [comment]
v2.1.3 has been released!
