### ISSUE TITLE
large memory footprint introduced by `chromadb` default embeddings

### ISSUE THREAD

**Issue by zzstoatzz** [PrefectHQ/marvin#83]
ChromaDB uses `sentence-transformers` by default for embeddings, which requires `torch`, which all together makes the footprint of chroma something like ~5GB.
  
We use OpenAI's `text-embedding-ada-002` model offered via `chromadb.utils.embedding_functions`, but
`chromadb` enforces the `sentence-transformers` dependency at this time.

We should find a way around this if chroma doesn't make `sentence-transformers` an optional dep

**Comment by jeffchuber** [comment]
@zzstoatzz chroma `0.4.0` is **much** smaller now.
