### ISSUE TITLE
add a doc on the logit bias trick

### ISSUE THREAD

**Issue by lostmygithubaccount** [PrefectHQ/marvin#855]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to look for a similar issue and didn't find it.
- [X] I searched the Marvin documentation for this feature.

### Describe the current behavior

I want to reference the logit bias trick sometimes; in particular, in an upcoming Ibis blog

currently, the best reference is [the Twitter thread](https://twitter.com/AAAzzam/status/1669753721574633473). it's also mentioned on [the classification docs page](https://www.askmarvin.ai/docs/text/classification/#classifying-text) with a link to that Twitter thread, but I think it'd be better to have a conceptual document or something on the Marvin website explaining the trick

### Describe the proposed behavior

add a doc for the logit bias trick (or add a dedicated section explaining it in the classification doc)

### Example Use

linking to it from Slack, blogs, etc.

### Additional context

it's an awesome trick :)

**Comment by Dev-Khant** [comment]
@zzstoatzz Can pick this up? Do I need to create a separate section for it or just elaborate it more in the current section itself?
