### ISSUE TITLE
Encoded image strings /w gpt-4-vision-preview

### ISSUE THREAD

**Issue by antoan** [PrefectHQ/marvin#861]
Is it currently possible to pass encoded image strings to Marvin, to extract structured data, rather than external urls?

Any thoughts would be much appreciated.

**Comment by zzstoatzz** [comment]
hi @antoan this should be possible as of #834 or `v2.2.2`

**Comment by zzstoatzz** [comment]
closing this, please let me know if 834 does not solve your issue
