### ISSUE TITLE
audio.speak: unexpected keyword argument 'openai_api_key'

### ISSUE THREAD

**Issue by lostmygithubaccount** [PrefectHQ/marvin#882]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

trying either example on the docs here: https://www.askmarvin.ai/docs/audio/speech

leads to a traceback:

```python
    332 async def generate_speech(
    333     self,
    334     input: str,
    335     file: Optional[Path] = None,
    336     **kwargs: Any,
    337 ) -> Optional["HttpxBinaryResponseContent"]:
--> 338     response = await self.client.audio.speech.create(
    339         input=input, **settings.openai.audio.speech.model_dump() | kwargs
    340     )
    341     if file:
    342         response.stream_to_file(file)

TypeError: AsyncSpeech.create() got an unexpected keyword argument 'openai_api_key'
```

### Reproduction

```python3
import marvin

audio = marvin.speak("I sure like being inside this fancy computer!")
```

### Error

```python3
TypeError: AsyncSpeech.create() got an unexpected keyword argument 'openai_api_key'
```

### Versions

```Text
Version:                2.3.0
Python version:         3.11.8
OS/Arch:                darwin/arm64
```

**Comment by lostmygithubaccount** [comment]
this might already be fixed on `main`?

**Comment by lostmygithubaccount** [comment]
or rather it's an openai version issue...

**Comment by lostmygithubaccount** [comment]
if you just pass `kwargs` through on this line, it works: https://github.com/openai/openai-python/blob/main/src/openai/resources/audio/speech.py#L127

which seems to be how it was on older versions of `openai`. but if I upgrade and try to use `marvin` I'm hitting other issues

**Comment by lostmygithubaccount** [comment]
so if I go back to `openai==1.13.4`, I get an error: `ImportError: cannot import name 'AssistantEventHandler' from 'openai'`

if I go above `openai==1.14.0` I get the above error

**Comment by lostmygithubaccount** [comment]
this is very annoying (on OpenAI Python SDK's part, not Marvin) but I'm unblocked I suppose by just patching `openai` to add (back?) the `**kwargs` input, not sure how y'all would want to handle all these breaking changes they seem to make in minor versions :)

**Comment by zzstoatzz** [comment]
hmmm - I almost wonder if this is a settings prefix issue again

if you just open ipython where you see the error and do something like
```python
import marvin

marvin.settings.openai.audio.speech.model_dump()
```

do you have a setting in there named `openai_api_key`?

**Comment by lostmygithubaccount** [comment]
I have both `marvin_openai_api_key` and `openai_api_key` set (to the same value)

**Comment by zzstoatzz** [comment]
woof, yeah. if you're willing to try a little surgery, I bet if you go [here](https://github.com/PrefectHQ/marvin/blob/main/src/marvin/settings.py#L147-L200) and make this
```python
class OpenAISettings(MarvinSettings):
    model_config = SettingsConfigDict(
        env_prefix="marvin_openai_",
        extra="ignore" # add this line
    )
```
that this would work

**Comment by lostmygithubaccount** [comment]
undoing my `openai` hack and adding that, I still get:

`TypeError: AsyncSpeech.create() got an unexpected keyword argument 'openai_api_key'`

**Comment by zzstoatzz** [comment]
hmm, so I can repro, do you have your api set in some `.env` file? or where is it coming from

**Comment by zzstoatzz** [comment]
oops hold on, speech settings redefines its own `SettingsConfigDict` so it doesnt inherit from `OpenAISettings`

try
```python
class SpeechSettings(MarvinSettings):
    """Settings for OpenAI's speech API.

    Attributes:
        model: The default speech model to use, defaults to `tts-1-hd`.
        voice: The default voice to use, defaults to `echo`.
        response_format: The default response format to use, defaults to `mp3`.
        speed: The default speed to use, defaults to `1.0`.
    """

    model_config = SettingsConfigDict(
        env_prefix="marvin_speech_", extra="ignore",
    )

    model: str = Field(
        default="tts-1-hd",
        description="The default model to use.",
    )
    voice: Literal["alloy", "echo", "fable", "onyx", "nova", "shimmer"] = Field(
        default="echo",
    )
    response_format: Literal["mp3", "opus", "aac", "flac"] = Field(default="mp3")
    speed: float = Field(default=1.0)
```

**Comment by zzstoatzz** [comment]
@lostmygithubaccount if you can confirm this work for you, I can get this released momentarily

**Comment by lostmygithubaccount** [comment]
@zzstoatzz that fixed it, appreciate the quick turnaround! installed from the PR and re-ran

**Comment by lostmygithubaccount** [comment]
oh and I'm setting environment variables in `~/.marvin/.env`

**Comment by zzstoatzz** [comment]
thanks for the report and context @lostmygithubaccount - [v2.3.1](https://github.com/PrefectHQ/marvin/releases/tag/v2.3.1) is out with the fix
