### ISSUE TITLE
Incorrect Docstring

### ISSUE THREAD

**Issue by Dev-Khant** [PrefectHQ/marvin#888]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Incorrect docstring written for `generate_speech` function. Can be checked [here](https://github.com/PrefectHQ/marvin/blob/d3e8e166d99b9d1a30a75748135b33dee8251250/src/marvin/ai/audio.py#L25).

### Reproduction

```python3
Can be see in code for `generate_speech()`.
```

### Error

```
    """
    Generates an image based on a provided prompt template.

    This function uses the DALL-E API to generate an image based on a provided
    prompt template. The function supports additional arguments for the prompt
    and the model.

    Args:
        prompt_template (str): The template for the prompt.
        prompt_kwargs (dict, optional): Additional keyword arguments for the
            prompt. Defaults to None.
        model_kwargs (dict, optional): Additional keyword arguments for the
            language model. Defaults to None.

    Returns:
        ImagesResponse: The response from the DALL-E API, which includes the
            generated image.
    """
```

### Versions

```Text
2.3.1
```

**Comment by Dev-Khant** [comment]
@zzstoatzz Can I fix this up?

**Comment by zzstoatzz** [comment]
@Dev-Khant yes please! thank you
