### ISSUE TITLE
Can't save audio to a file

### ISSUE THREAD

**Issue by Dev-Khant** [PrefectHQ/marvin#892]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

After generating speech using `marvin.speak` I'm unable to save it a audio file.

### Reproduction

```python3
import marvin

audio = marvin.speak("I sure like being inside this fancy computer!")
audio.stream_to_file("fancy_computer.mp3")
```

### Error

```python3
Traceback (most recent call last):
  File "/Users/darshit/Desktop/marvin/temp.py", line 8, in <module>
    audio.stream_to_file("fancy_computer.mp3")
    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/darshit/Desktop/marvin/.venv/lib/python3.11/site-packages/pydantic/main.py", line 767, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Audio' object has no attribute 'stream_to_file'
```

### Versions

```Text
2.3.1
```

**Comment by Dev-Khant** [comment]
@zzstoatzz Can I work on this?

**Comment by zzstoatzz** [comment]
> @zzstoatzz Can I work on this?

PRs are always welcome 🙂
