### ISSUE TITLE
details-and-few-shot-examples specs dont do anything?

### ISSUE THREAD

**Issue by victorthevong** [PrefectHQ/marvin#903]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

https://www.askmarvin.ai/docs/text/classification/#details-and-few-shot-examples

This example seems to outline the use of project specs to enhance few shot classification?

However I fail to see where if at all the actual project spec descriptions is ever passed to marvin. It seems like any other use of classify just passing in labels and trying to let the model figure it out based on labels alone?

Am I missing something here or what is the point of project specs otherwise if it isnt ever passed to marvin.classify?

### Reproduction

```python3
The example link showcases the direct code controversy
```

### Versions

```Text
v2.3.1
```

**Comment by zzstoatzz** [comment]
hi @victorthevong - thanks for the issue!

it seems to me that 
> Details and few-shot examples
is just not an appropriate title for this section of docs, since you're right that the values of the `dict` are not passed to the LLM.
