### ISSUE TITLE
Audio#record should  return Audio Type ?

### ISSUE THREAD

**Issue by hirokidaichi** [PrefectHQ/marvin#918]
https://github.com/PrefectHQ/marvin/blob/f4ec4eef128d6264849e5fa6e4f99134258fafbb/src/marvin/audio.py#L121

I apologize if my understanding of the code was incorrect. In the part where the Audio object is supposed to be returned, there seem to be two return statements, exposing different data types.

**Comment by zzstoatzz** [comment]
thanks for the issue @hirokidaichi - yes this was a mistake. we should be returning the right audio type here now
