### ISSUE TITLE
[Question] Limited Configurability with tiktoken Dependency or Caching

### ISSUE THREAD

**Issue by ThomasBury** [PrefectHQ/marvin#958]
I'm encountering a challenge when using Marvin due to its dependency on tiktoken. Tiktoken cannot currently pass request kwargs, for proxy, verify, etc. (required on enterprise networks)

While setting tiktoken to [offline mode](https://stackoverflow.com/questions/76106366/how-to-use-tiktoken-in-offline-mode-computer) could be a potential solution, this approach is inconvenient for testing purposes.   

Is there a documented solution that I missed?

thank you

**Comment by zzstoatzz** [comment]
hi @ThomasBury - there's nothing you missed AFAIK

I think we could probably add an opt-in setting that saves the cache to the `~/.marvin` directory - how does that sound?

**Comment by zzstoatzz** [comment]
@ThomasBury - I've opened https://github.com/PrefectHQ/marvin/pull/962 to address this, could you try it out?

**Comment by ThomasBury** [comment]
That sounds great! Thank you for looking into this. Documenting this solution as a cookbook would be an excellent next step.
