### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by thakurboy004** [PrefectHQ/marvin#983]
While scrolling through the README.md, I noticed that the procedure for reporting a bug is unclear and improperly merged into the README file, which is not a good documentation practice. I would like to address this by creating a separate file to guide users through the bug-reporting process in a structured manner, following your policy. 😊

If this issue is accepted, I am happy to open a pull request to resolve it. 🔧✨

**Comment by zzstoatzz** [comment]
hi @thakurboy004 - I'm not sure we need a `SECURITY.md`, but if you have a specific proposal for updating the README to make it more clear, im happy to review the PR

**Comment by thakurboy004** [comment]
Okay I would be happy to do that

**Comment by thakurboy004** [comment]
Hi @zzstoatzz I have successfully made some changes in the README file which incorporates all the required information of the SECURITY.md file for further more information, Please refer to PR #985
